[[Repositories]]
name = "master"
origin = "ACME Inc."

[[Components]]
name = "main"
summary = "Supported Packages"

[[Architectures]]
name = "amd64"
summary = "AMD x86-64 architecture"

[[Architectures]]
name = "arm64"
summary = "64-Bit ARM"

[[Uploaders]]
repo_name = "master"
email = "testuser@example.org"
fingerprints = ["DEADBEEF"]
is_human = true

[[Suites]]
name = "unstable"
alias = ""
summary = "Development Suite"
version = "2.0"
arch_names = ["amd64", "arm64"]
component_names = ["main"]

[[Suites]]
name = "stable"
alias = ""
summary = "Stable 1.0 Release"
version = "1.0"
arch_names = ["amd64", "arm64"]
component_names = ["main"]

[[RepoSuiteSettings]]
repo_name = "master"
suite_name = "unstable"
signingkeys = ["DEADBEEF"]
announce_emails = []

[[RepoSuiteSettings]]
repo_name = "master"
suite_name = "stable"
signingkeys = ["DEADBEEF"]
announce_emails = []
